1. Write a Python Program to Add Two Matrices?

In [59]:
import numpy as np

In [60]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,1],[2,2]])
a+b

array([[2, 3],
       [5, 6]])

In [61]:
a = np.arange(1,10)
a.reshape(3,3)

b = np.arange(1,10)
b.reshape(3,3)

print((a+b).reshape(3,3))

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


2. Write a Python Program to Multiply Two Matrices?

In [62]:
a = np.array([[1,2],
              [3,4]])

b = np.array([[1,1],
              [2,2]])
a*b

array([[1, 2],
       [6, 8]])

3. Write a Python Program to Transpose a Matrix?

In [63]:
a = np.array([[1,2,3,10],
              [3,-4,5,8]])
transposed_arr = np.transpose(a)
transposed_arr


array([[ 1,  3],
       [ 2, -4],
       [ 3,  5],
       [10,  8]])

4. Write a Python Program to Sort Words in Alphabetic Order?

In [64]:
def to_sort(words):
  if type(words)==list:
    return ' '.join(sorted(words))      # for list of words
  else:
    return ''.join(sorted(words))         # for single words 

In [65]:
lst = ['hello','world','bike','eye','wow','house']
to_sort(lst)


'bike eye hello house world wow'

In [66]:
to_sort('PythonHelloWorld')

'HPWdehlllnooorty'

5. Write a Python Program to Remove Punctuation From a String?


In [67]:
import string
def to_remove(sentence): 
   new_sen = ''                  # to make new string 
   # Get the set of punctuation marks
   punctuation_marks = set(string.punctuation)      # set of all puctucation marks present in the string library
   for i in sentence:
    if i not in punctuation_marks:
      new_sen = new_sen + i
   return new_sen

In [68]:
sen = "The thunder roared, rain poured relentlessly, and the wind howled fiercely, creating a symphony of nature's fury! "
to_remove(sen)

'The thunder roared rain poured relentlessly and the wind howled fiercely creating a symphony of natures fury '